"""Update models for authentication support

Revision ID: fe0d19b4cab1
Revises: 4f46ec21196b
Create Date: 2017-03-24 23:01:58.702933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0d19b4cab1'
down_revision = '4f46ec21196b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_roles_email'), 'roles', ['email'], unique=True)
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_roles_email'), table_name='roles')
    op.drop_column('roles', 'email')
    # ### end Alembic commands ###
